---

# TODO: handle weird shell naming cases?
# ie. 'bash-5.1' instead of 'bash'
- name: setup
  include_vars: "{{ ansible_user_shell | basename }}.yml"
  tags: always

#####=== install ===#####

- block:
  - name: fish/zsh | install | create installation directory
    file: path="{{ pure_install_dir }}" state=directory follow=yes

  - name: fish/zsh | install
    get_url:
      url: "{{ pure_url }}/{{ item.name }}"
      dest: "{{ pure_install_dir }}/{{ item.dest | default(item.name) }}"
      force: yes
    with_items: "{{ pure_files }}"
  when: pure_files is defined
  tags:
    - bootstrap
    - bootstrap_pure
    - install
    - install_pure
    - update
    - update_pure

#####=== configure ===#####

# TODO: use sindresorhus/pure for bash if it is compatible
- name: bash/zsh | configure | shell initialization
  blockinfile:
    dest: "{{ pure_config_file }}"
    create: yes
    backup: no
    state: "{{ pure_configure_state }}"
    marker: "{{ pure_marker }}"
    block: "{{ pure_config_block }}"
  when: pure_config_block is defined
  tags:
    - bootstrap
    - bootstrap_pure
    - configure
    - configure_pure
